### PR TITLE
Class decompozition

### PR DESCRIPTION
**Pull request by alimovlex**
Hello!

I saw your code is not maintained. Therefore, I have made classes decompozition.
In my view, the code seems now more readable.

### CODE REVIEW

**Comment by alimovlex** [comment]
I also untethered hardcoded api.ini file and made reading data from the command-line arguments.

**Comment by alimovlex** [comment]
Switched from the command line arguments and took app_id and api_hash from the tdlib example provided.

**Comment by alimovlex** [comment]
Refactored code.

**Comment by jackguo** [comment]
Thanks for the effort! 
Do like the idea of splitting the classes into their own cpp files. It looks like you already have the code in your own repo, I will no bother merging this one.

**Comment by jackguo** [comment]
I recently have some new ideas to experiment with, to see if can optimize the multithreading design here. But I will definitely take your advice and split the classes later, will quote you in the commit!

**Comment by alimovlex** [comment]
Thanks. I am going to try multi threading in your client too!

**Comment by jackguo** [comment]
Going to close this one, addressed in https://github.com/jackguo/telegram-clients/pull/6

**Comment by alimovlex** [comment]
@jackguo, Thanks.

**Pull request closed without merging**
